---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

# dataset:
#   # dataset config

# model:
#   # model config

# strategy:
#   _target_: # points to your strategy (either custom or exiting in Flower)
#   # rest of strategy config

# client:
#   # client config




# dataset_config
# dataset_config
num_clients: 100
num_epochs: 5
num_rounds: 400
seed: 0
client_device: 'cuda'
device: 'cpu'

control:
  model_split_rate: 'fix'
  model_mode: 'a5-e5'

dataset_config:
  dataset_name: 'CIFAR10'
  iid: True
  shard_per_user : 2 # only used in case of non-iid (i.e. iid = false)
  balance: false
  batch_size:
    train: 10
    test: 50
  shuffle:
    train: true
    test: false


model:
  model_name: resnet18
  hidden_layers: [64 , 128 , 256 , 512]
  norm: bn

strategy:
  optimizer: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 5.00e-04
  scheduler: MultiStepLR
  milestones: [150 , 250]

